version: '3.8'

services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY}:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/concert
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    restart: on-failure
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=concert
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: